---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize }}
...
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-postgresql
    app: postgresql
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgresql.env.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.postgresql.env.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.env.POSTGRES_PASSWORD | quote }}
...
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-postgresql
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - port: {{ .Values.postgresql.containerPort }}
      targetPort: {{ .Values.postgresql.containerPort }}
  type: ClusterIP
...
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-postgresql
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sausage-postgresql
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: postgresql-creds
          ports:
            - containerPort: {{ .Values.postgresql.containerPort }}
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["bash", "-c", "psql -w -U $POSTGRES_USER -d $POSTGRES_DB SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["bash", "-c", "psql -w -U $POSTGRES_USER -d $POSTGRES_DB SELECT 1"]
            initialDelaySeconds: 30
            timeoutSeconds: 2
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc
...
